# Generated by Django 2.0.9 on 2018-12-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181205_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты'},
        ),
    ]
