# Generated by Django 2.0.9 on 2018-12-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181127_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Список домов', 'verbose_name_plural': 'Список домов'},
        ),
    ]
