# Generated by Django 2.0.9 on 2018-12-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20181127_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Риэлторы', 'verbose_name_plural': 'Риэлторы'},
        ),
    ]
